// tweetlib - A fully oauth-authenticated Go Twitter library
//
// Copyright 2011 The Tweetlib Authors.  All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package tweetlib

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"net/http"
	"reflect"
)

var _ = reflect.TypeOf

const (
	// URL to post tweets
	postURL = "http://api.twitter.com/1.1/statuses/update.json"
	// General URL for API calls
	apiURL = "https://api.twitter.com/1.1"
)

// twitterError represents an error generated by
// the Twitter API
type twitterError struct {
	Message string `json:message` // Error message
	Code    int    `json:code`    // Error code
}

// twitterErrorReply: contains a list of errors returned
// for a request to the Twitter API
type twitterErrorReply struct {
	Errors []twitterError `json:errors`
}

// Twitter error responses can actually contain
// multiple errors. This function preps them
// for a nice display
func (ter *twitterErrorReply) String() string {
	buf := bytes.NewBufferString("")
	for i := range ter.Errors {
		fmt.Fprintf(buf, "%s (%d)\n", ter.Errors[i].Message, ter.Errors[i].Code)
	}
	return buf.String()
}

// Checks whether the response is an error
func checkResponse(res *http.Response) (err error) {
	if res.StatusCode >= 200 && res.StatusCode <= 299 {
		return nil
	}
	slurp, err := ioutil.ReadAll(res.Body)
	fmt.Printf("%s\n", slurp)
	if err != nil {
		return err
	}
	var jerr twitterErrorReply
	if err = json.Unmarshal(slurp, &jerr); err != nil {
		return
	}
	return errors.New(jerr.String())
}

// Creates a new twitter client
func New(transport *Transport) (*Client, error) {
	if transport.Client() == nil {
		return nil, errors.New("client is nil")
	}
	c := &Client{client: transport.Client()}
	c.Help = &HelpGroup{c}
	c.DM = &DMGroup{c}
	c.Tweets = &TweetsGroup{c}
	c.Account = &AccountGroup{c}
	return c, nil
}

// Client: Twitter API client provides access to the various
// API services
type Client struct {
	client *http.Client

	// Twitter's 'statuses' function group
	Tweets *TweetsGroup

	// Direct Messages function group
	DM *DMGroup

	// Twitter's Help function group
	Help *HelpGroup

	// Account functiona group
	Account *AccountGroup
}

// Performs an arbitrary API call and returns the response JSON if successful.
// This is generally used internally by other functions but it can also
// be used to perform API calls not directly supported by tweetlib.
//
// For example
//
//   opts := NewOptionals()
//   opts.Add("status", "Hello, world")
//   rawJSON, _ := client.CallJSON("POST", "statuses/update_status", opts)
//   var tweet Tweet
//   err := json.Unmarshal(rawJSON, &tweet)
//
// is the same as
//
//   tweet, err := client.UpdateStatus("Hello, world", nil)
func (c *Client) CallJSON(method, endpoint string, opts *Optionals) (rawJSON []byte, err error) {
	if method != "GET" && method != "POST" {
		err = fmt.Errorf("Invalid method '%s'. Must be either GET or POST.", method)
		return
	}
	if opts == nil {
		opts = NewOptionals()
	}
	endpoint = fmt.Sprintf("%s/%s.json?%s", apiURL, endpoint, opts.Values.Encode())
	fmt.Println(endpoint)
	var req *http.Request
	if method == "POST" {
		body := bytes.NewBuffer([]byte(opts.Values.Encode()))
		req, _ = http.NewRequest(method, endpoint, body)
		req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	} else {
		req, _ = http.NewRequest(method, endpoint, nil)
	}
	res, err := c.client.Do(req)
	if err != nil {
		return
	}
	if err = checkResponse(res); err != nil {
		return
	}
	rawJSON, err = ioutil.ReadAll(res.Body)
	return
}

// Performs an arbitrary API call and tries to unmarshal the result into
// 'resp' on success. This is generally used internally by the other functions
// but it could be used to perform unsupported API calls.
//
// Example usage:
//
//     var tweet Tweet
//     opts := NewOptionals()
//     opts.Add("status", "Hello, world")
//     err := client.Call("POST", "statuses/update_status", opts, &tweet)
//
// is equivalent to
//
//     tweet, err := client.UpdateStatus("Hello, world", nil)
func (c *Client) Call(method, endpoint string, opts *Optionals, resp interface{}) (err error) {
	rawJSON, err := c.CallJSON(method, endpoint, opts)
	if err != nil {
		return
	}
	if resp != nil {
		if err = json.Unmarshal(rawJSON, resp); err != nil &&
			reflect.TypeOf(err) != reflect.TypeOf(&json.UnmarshalTypeError{}) {
			return err
		}
	}
	return nil
}

// Provides a simple, relevance-based search interface to public user accounts
// on Twitter. Try querying by topical interest, full name, company name,
// location, or other criteria. Exact match searches are not supported.
// See https://dev.twitter.com/docs/api/1.1/get/users/search
func (c *Client) Search(q string, opts *Optionals) (tweets *TweetList, err error) {
	if opts == nil {
		opts = NewOptionals()
	}
	opts.Add("q", q)
	tweets = &TweetList{}
	err = c.Call("GET", "users/search", opts, tweets)
	return
}
